spring:
  ## maven面板动态切换dev/pro环境
  profiles:
    active: "@profiles.active@"
  ## 项目名
  application:
    name: xj-base-admin
  ## 当遇到同样beng名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  ## 关闭thymeleaf缓存 开发时使用,否则没有实时画面
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  ## 时间格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 1024MB      # 单个文件的最大上限
      max-request-size: 1024MB   # 单个请求的文件总大小上限

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 代码生成配置
gc:
  # 代码生成后每个类上的描叙信息
  describe: ::本代码由[兮家小二]提供的代码生成器生成,如有问题,请手动修改 ::作者CSDN:https://blog.csdn.net/qq_41463655
  author: ws                              # 作者
  email: 1720696548@qq.com                # 邮箱
  projectName: spring-boot-plus2-demo     # 项目名/路径，如：xj-server/xj-test-server
  packPath: com.test.springbootplus2      # 包路径
  rootModule: manage                      # 根模块(固定为：manage (管理端), 用户端为：client)
  moduleName: test1                       # 子模块(如用户管理,订单管理模块拆分，也可以统一一个名称放在一起,但不建议)
  tablePrefixDefault: t_                  # 表前缀 (生成的类名会过滤掉前缀)
  fieldPrefixDefault:                     # 字段前缀 (生成的字段名会过滤掉前缀)
  entitySwagger: false                    # 实体类是否使用swagger注释 (false情况下使用doc注释)
  fatherPath:                             # 生成路径(不填默认当前项目跟目录,可指定绝对路径)
  # 数据库通用字段配置
  basefields: id,create_user,update_user,create_time,update_time,deleted,version
  # 数据库关键字,标注后会在实体类 @TableField 注解上自动加引号
  keywordArray: time,desc,name,key,value,mysql,info,form,sort,icon,unlock,unLock,comment,disable,force,describe


