spring:
  profiles:
    # maven面板动态切换dev/pro环境
    active: @profiles.active@

  # 当遇到同样beng名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true

  # 关闭thymeleaf缓存 开发时使用,否则没有实时画面
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

  #时间格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  # Spring Boot Admin 配置 actuator监控中心可视化界面   /bootAdmin
#  boot:
#    admin:
#      context-path: /bootAdmin
#      ui:
#        title: SpringBootAdmin-Server
#      client:
#        ## server地址
#        url: http://localhost:${server.port}${spring.boot.admin.context-path}
#        ## 指定服务器的用户名和密码
#        username: admin
#        password: admin
#        instance:
#          # client地址
#          service-base-url: http://localhost:${server.port}
#          ## 连接服务器的用户名和密码
#          metadata:
#            user:
#              name: admin
#              password: admin
  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 1024MB      # 单个文件的最大上限
      max-request-size: 1024MB   # 单个请求的文件总大小上限

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.ws.ldy.enums.*
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




# Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
#management:
#  endpoints:
#    web:
#      exposure:
#        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
#        include: "*"
#  endpoint:
#    health:
#      # 是否展示健康检查详情
#      show-details: ALWAYS

### 屏蔽swagger+ 无默认值错误日志
#logging:
#  ## 日志文件位置
#  #file: F:\workspace\code\git2020-4\spring-boot-plus2\logs\info\log.log.0
#  file: log.txt
#  level:
#    io.swagger.models.parameters.AbstractSerializableParameter: error
#    com.alibaba.nacos.client.naming: error
