
server:
  port: 8080   # HTTP (Tomcat) port
#  servlet:
#    context-path: /adminconsole   # 配置项目名 47.107.128.84
  ### 数据源，服务名称
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
