spring:
  profiles:
    active: pro
  #当遇到同样beng名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  # 第一次建表create  后面用update
  #  create 启动时删数据库中的表，然后创建，退出时不删除数据表
  #  create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
  #  update 如果启动时表格式不一致则更新表，原有数据保留
  #  validate 项目启动表结构进行校验 如果不一致则报错
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # 控制台是否打印sql
  # 关闭thymeleaf缓存 开发时使用 否则没有实时画面
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  #时间格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

### 屏蔽swagger+ 无默认值错误日志
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com.alibaba.nacos.client.naming: error
#    io:
#      swagger:
#        models:
#          parameters:
#            AbstractSerializableParameter: error