## 正式环境

## HTTP (Tomcat) port
server:
  port: 9049

# DataSource Config spring.datasource.dynamic.datasource.db1.url
spring:
  autoconfigure:
    # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      # | rewriteBatchedStatements=true mybatis批处理优化 | useTimezone=true&serverTimezone=GMT%2B8  使用北京时间 | useUnicode=true&characterEncoding=utf-8 编码 |
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: root123456
          type: com.alibaba.druid.pool.DruidDataSource


## 通用模块环境配置 true 正式环境 | false 测试环境(默认)
xj:
  isAliOss: true     # 阿里云OSS配置 --> OssConfig
  isQiNiuOss: true   # 七牛云OSS配置 --> QiNiuConfig
  isWxMp: true       # 微信公众号配置 --> WxMpConfig
  isWxPay: true      # 微信支付配置   --> WxPay2Config


## logback日志输出：linux 项目放置路径, 请自行配置log在服务器的输出路径，由 logback-spring.xml 读取此配置信息, 线上请配置linux路径: /usr/local/work/xijia2/logs
logging:
  # 日志目录, 线上请配置linux 绝对路径 如：/usr/local/work/xijia2/logs
  filePath: /usr/local/work/xijia2/logs
  # 配置日志路径即可实时输出到 spring-boot-admin 日志管理
  file: /usr/local/work/xijia2/log.txt

