## 生产环境

## HTTP (Tomcat) port
server:
  port: 9049

# DataSource Config spring.datasource.dynamic.datasource.db1.url
spring:
  autoconfigure:
    # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      # | rewriteBatchedStatements=true mybatis批处理优化 | useTimezone=true&serverTimezone=GMT%2B8  使用北京时间 | useUnicode=true&characterEncoding=utf-8 编码 |
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username:
          password:
          type: com.alibaba.druid.pool.DruidDataSource

## 阿里云api
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
    bucket:

# 日志配置, filePath线上日志存放地址（logback-spring.xml 读取） , methods 记录那些请求数据到数据库
logging:
  filePath: /usr/local/work/xijia2/logs
  methods: POST,PUT,DELETE

