
server:
  port: 10001

spring:
  ## 关闭thymeleaf缓存 开发时使用,否则没有实时画面
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html



